version: '3'

services:
  proxy:
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certbot/conf:/etc/nginx/ssl:ro
      - ./certbot/data:/var/www/certbot:ro
    environment:
      - ENVIRONMENT=production

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=https://api.gosystemslab.com
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
    environment:
      - ENVIRONMENT=production
      - DEBUG=0

  certbot:
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/data:/var/www/certbot:rw
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email -d app.${DOMAIN} -d api.${DOMAIN} -d adminer.${DOMAIN} 