version: '3'

services:
  proxy:
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      - ENVIRONMENT=production

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production

  backend:
    environment:
      - ENVIRONMENT=production
      - DEBUG=0
    ports:
      - "8000:8000"

  # Disable certbot temporarily
  certbot:
    profiles:
      - disabled
