version: '3'

services:

  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default


  backend:
    #image: jakeevica/backend:latest
    build: ./backend
    ports:
      - "8000:8000"
#    environment:
 #     - SECRET_KEY=evib2IdXmCZ0sM6nBW61Ak5PMEoRSaf7bvxal59_E_A

    depends_on:
      db:
        condition: service_healthy
 #   env_file:
  #    - .env

    volumes:
      - .env:/app/.env 
    networks:
      - default

  frontend:
    image: jakeevica/frontend:latest
    build: ./frontend
#    ports:
 #     - 3000:80
  #  volumes:
   #   - ./frontend/nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - default

volumes:
  app-db-data:

networks:
  default:
    name: app-network
