version: '3'

services:
  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd:ro
    depends_on:
      - frontend
      - backend
      - adminer
    networks:
      - default
    restart: always

  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} -d app.${DOMAIN} -d api.${DOMAIN} -d adminer.${DOMAIN} --agree-tos --non-interactive --force-renewal
    networks:
      - default
    depends_on:
      - nginx

networks:
  default:
    external: true 