name: app
services:
  adminer:
    depends_on:
      db:
        condition: service_started
        required: true
    expose:
      - "8080"
    image: adminer:4
    networks:
      default: null
  backend:
    depends_on:
      db:
        condition: service_healthy
        required: true
      prestart:
        condition: service_completed_successfully
        required: true
    environment:
      BACKEND_CORS_ORIGINS: '["https://app.gosystemslab.com","https://api.gosystemslab.com"]'
      DO_AUTH_TOKEN: your_digital_ocean_api_token_here
      DOCKER_IMAGE_BACKEND: jakeevica/backend
      DOCKER_IMAGE_FRONTEND: jakeevica/frontend
      DOMAIN: gosystemslab.com
      EMAIL: jake@gosystemslab.com
      EMAILS_FROM_EMAIL: info@gosystemslab.com
      ENVIRONMENT: production
      FIRST_SUPERUSER: admin@gosystemslab.com
      FIRST_SUPERUSER_PASSWORD: Gwz3IHioGp49545X15ayXA
      FRONTEND_HOST: https://app.gosystemslab.com
      HASHED_PASSWORD: $$2y$$10$$qxpv5qZUWxuYGCqxqDXKIeYwYf5GSqk4t0SzEsYbLY1B6j9pwPkhu
      POSTGRES_DB: app
      POSTGRES_PASSWORD: hgZ_8RLrn0L81eCrV7X5BA
      POSTGRES_PORT: "5432"
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      PROJECT_NAME: GoSystems Lab Dashboard
      SECRET_KEY: 6l3Piro9VfN-mydHOPYDdGutIzIJeKObIt47FEDnt7w
      SENTRY_DSN: https://54775bcfd73bde71044ce49de6b97060@o4509034710237184.ingest.us.sentry.io/4509036081643520
      SMTP_HOST: ""
      SMTP_PASSWORD: ""
      SMTP_PORT: "587"
      SMTP_SSL: "False"
      SMTP_TLS: "True"
      SMTP_USER: ""
      STACK_NAME: gosystems-dashboard
      USERNAME: admin
    expose:
      - "8000"
    image: jakeevica/backend:latest
    networks:
      default: null
  certbot:
    command:
      - certonly
      - --webroot
      - --webroot-path=/var/www/html
      - --email
      - jake@gosystemslab.com
      - -d
      - app.gosystemslab.com
      - -d
      - api.gosystemslab.com
      - -d
      - adminer.gosystemslab.com
      - --agree-tos
      - --non-interactive
      - --force-renewal
    depends_on:
      nginx:
        condition: service_started
        required: true
    image: certbot/certbot
    networks:
      default: null
    volumes:
      - type: bind
        source: /root/app/nginx/ssl
        target: /etc/letsencrypt
        bind:
          create_host_path: true
      - type: bind
        source: /root/app/nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
        bind:
          create_host_path: true
  db:
    environment:
      BACKEND_CORS_ORIGINS: '["https://app.gosystemslab.com","https://api.gosystemslab.com"]'
      DO_AUTH_TOKEN: your_digital_ocean_api_token_here
      DOCKER_IMAGE_BACKEND: jakeevica/backend
      DOCKER_IMAGE_FRONTEND: jakeevica/frontend
      DOMAIN: gosystemslab.com
      EMAIL: jake@gosystemslab.com
      EMAILS_FROM_EMAIL: info@gosystemslab.com
      ENVIRONMENT: production
      FIRST_SUPERUSER: admin@gosystemslab.com
      FIRST_SUPERUSER_PASSWORD: Gwz3IHioGp49545X15ayXA
      FRONTEND_HOST: https://app.gosystemslab.com
      HASHED_PASSWORD: $$2y$$10$$qxpv5qZUWxuYGCqxqDXKIeYwYf5GSqk4t0SzEsYbLY1B6j9pwPkhu
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: app
      POSTGRES_PASSWORD: hgZ_8RLrn0L81eCrV7X5BA
      POSTGRES_PORT: "5432"
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      PROJECT_NAME: GoSystems Lab Dashboard
      SECRET_KEY: 6l3Piro9VfN-mydHOPYDdGutIzIJeKObIt47FEDnt7w
      SENTRY_DSN: https://54775bcfd73bde71044ce49de6b97060@o4509034710237184.ingest.us.sentry.io/4509036081643520
      SMTP_HOST: ""
      SMTP_PASSWORD: ""
      SMTP_PORT: "587"
      SMTP_SSL: "False"
      SMTP_TLS: "True"
      SMTP_USER: ""
      STACK_NAME: gosystems-dashboard
      USERNAME: admin
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -U postgres
      timeout: 5s
      interval: 5s
      retries: 5
    image: postgres:12
    networks:
      default: null
    volumes:
      - type: volume
        source: app-db-data
        target: /var/lib/postgresql/data/pgdata
        volume: {}
  frontend:
    expose:
      - "80"
    image: jakeevica/frontend:latest
    networks:
      default: null
  nginx:
    depends_on:
      adminer:
        condition: service_started
        required: true
      backend:
        condition: service_started
        required: true
      frontend:
        condition: service_started
        required: true
    image: nginx:1.25
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "80"
        protocol: tcp
      - mode: ingress
        target: 443
        published: "443"
        protocol: tcp
    restart: always
    volumes:
      - type: bind
        source: /root/app/nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /root/app/nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /root/app/nginx/ssl
        target: /etc/nginx/ssl
        read_only: true
        bind:
          create_host_path: true
      - type: bind
        source: /root/app/nginx/.htpasswd
        target: /etc/nginx/.htpasswd
        read_only: true
        bind:
          create_host_path: true
  prestart:
    depends_on:
      db:
        condition: service_healthy
        required: true
    environment:
      BACKEND_CORS_ORIGINS: '["https://app.gosystemslab.com","https://api.gosystemslab.com"]'
      DO_AUTH_TOKEN: your_digital_ocean_api_token_here
      DOCKER_IMAGE_BACKEND: jakeevica/backend
      DOCKER_IMAGE_FRONTEND: jakeevica/frontend
      DOMAIN: gosystemslab.com
      EMAIL: jake@gosystemslab.com
      EMAILS_FROM_EMAIL: info@gosystemslab.com
      ENVIRONMENT: production
      FIRST_SUPERUSER: admin@gosystemslab.com
      FIRST_SUPERUSER_PASSWORD: Gwz3IHioGp49545X15ayXA
      FRONTEND_HOST: https://app.gosystemslab.com
      HASHED_PASSWORD: $$2y$$10$$qxpv5qZUWxuYGCqxqDXKIeYwYf5GSqk4t0SzEsYbLY1B6j9pwPkhu
      POSTGRES_DB: app
      POSTGRES_PASSWORD: hgZ_8RLrn0L81eCrV7X5BA
      POSTGRES_PORT: "5432"
      POSTGRES_SERVER: db
      POSTGRES_USER: postgres
      PROJECT_NAME: GoSystems Lab Dashboard
      SECRET_KEY: 6l3Piro9VfN-mydHOPYDdGutIzIJeKObIt47FEDnt7w
      SENTRY_DSN: https://54775bcfd73bde71044ce49de6b97060@o4509034710237184.ingest.us.sentry.io/4509036081643520
      SMTP_HOST: ""
      SMTP_PASSWORD: ""
      SMTP_PORT: "587"
      SMTP_SSL: "False"
      SMTP_TLS: "True"
      SMTP_USER: ""
      STACK_NAME: gosystems-dashboard
      USERNAME: admin
    image: jakeevica/backend:latest
    networks:
      default: null
networks:
  default:
    name: app-network
    external: true
volumes:
  app-db-data:
    name: app_app-db-data
