version: '3'

services:
  proxy:
    ports:
      - "80:80"
    volumes:
      - ./nginx/local.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    environment:
      - ENVIRONMENT=local

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://api.gosystemslab.com
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/.venv
    environment:
      - ENVIRONMENT=local
      - DEBUG=1
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

  # Disable certbot in development
  certbot:
    profiles:
      - production 