"""Add Amazon Ads token fields to user

Revision ID: 6d492f1b56d0
Revises: 1a31ce608336
Create Date: 2025-04-02 08:43:54.019931

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6d492f1b56d0'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('amazon_ads_encrypted_access_token', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('amazon_ads_encrypted_refresh_token', sa.LargeBinary(), nullable=True))
    op.add_column('user', sa.Column('amazon_ads_token_expiry', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'amazon_ads_token_expiry')
    op.drop_column('user', 'amazon_ads_encrypted_refresh_token')
    op.drop_column('user', 'amazon_ads_encrypted_access_token')
    # ### end Alembic commands ###
